// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATRKjsURXJTmwGbRiONJLHIf39VSab7Fc',
    appId: '1:443771459912:web:8eee05ca6d97511a30fb7d',
    messagingSenderId: '443771459912',
    projectId: 'bloodsos-f82d3',
    authDomain: 'bloodsos-f82d3.firebaseapp.com',
    storageBucket: 'bloodsos-f82d3.firebasestorage.app',
    measurementId: 'G-XRTMLEPH1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXTPxivUpE3wYysNf9ZiqMQSUuGpQksvA',
    appId: '1:443771459912:android:e90aea183fca590430fb7d',
    messagingSenderId: '443771459912',
    projectId: 'bloodsos-f82d3',
    storageBucket: 'bloodsos-f82d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj37b7K37PWZ3-M0JnoIHstOUgE6dXa6U',
    appId: '1:443771459912:ios:6ca9b43c31539ace30fb7d',
    messagingSenderId: '443771459912',
    projectId: 'bloodsos-f82d3',
    storageBucket: 'bloodsos-f82d3.firebasestorage.app',
    iosBundleId: 'com.example.bloodSos',
  );
}
